name: ladonware
recipe: laravel
config:
  webroot: public
  php: '8.0'
  xdebug: true
  conf:
    php: .vscode/php.ini
services:
  appserver:
    webroot: public
    xdebug: true
    config:
      php: .vscode/php.ini
  phpmyAdmin:
    type: phpmyadmin
    hosts:
      - database
